[package]
name = "icarus_envy"
version = "0.3.2"
edition = "2024"
rust-version = "1.88"

[dependencies]
dotenvy = { version = "0.15.7" }
const_format = { version = "0.2.34" }

[dev-dependencies]
async-std = { version = "1.13.1" }
